# -*- coding: utf-8 -*-
"""Praktikum03_Kelompok 19

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T8p9tDPZyDWUqiih-J4NmJQzxQifk6Fk

Praktikum 3: Matplotlib - Line Plot
Kelompok 19:


*   Dewi Nuraini - 0110122122
*   Muhammad Daffa Shafwan - 0110222275
*   Muhammad Saputra Adi Firmansyah - 0110222105

Import Library
"""

import matplotlib.pyplot as plt

"""Dataset"""

# Buat data sample
months = ['Jan', 'Feb', 'Mar', 'Apr', 'Mei', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Des']
product_A_sales = [10,20,15,25,30,45,40,50,60,55,65,70]
product_B_sales = [5,10,8,15,18,20,22,30,25,35,40,45]

"""Single Line Plot"""

# line plot 1 garis, style grafik default
plt.plot(months, product_A_sales, label='Product A')
plt.title('Penjualan Produk per Bulan')
plt.xlabel('Bulan')
plt.ylabel('Penjualan')
plt.legend()
plt.grid(True)
plt.show()

"""Multiple Line Plot & Customization"""

#Kustomisasi line plot (line 1 - product a)
plt.plot(months, product_A_sales, label='Product A', linestyle="--", marker='o')

#Kustomisasi line plot(line 1 - product b)
plt.plot(months, product_B_sales, label='Product B', linestyle="--", marker='x')

plt.title('Penjualan Produk A per Bulan')
plt.xlabel('Bulan')
plt.ylabel('Penjualan')
plt.legend()
plt.grid(True)
plt.show()

"""Jenis Garis unutk Menunjukkan Tren"""

# Data sample tambahan
product_C_sales = [18,22,25,28,32,38,42,45,48,52,56,60]
product_D_sales = [7,9,11,13,16,18,20,23,25,28,30,33]

# plot product A
plt.plot(months, product_A_sales, label='Product A', linestyle="--", color='blue')

# plot product B
plt.plot(months, product_B_sales, label='Product B', linestyle="-", color='red')

# plot product C
plt.plot(months, product_C_sales, label='Product C', linestyle=":", color='green')

# plot product D
plt.plot(months, product_D_sales, label='Product D', linestyle="-.", color='purple')


plt.title('Penjualan Produk A per Bulan')
plt.xlabel('Bulan')
plt.ylabel('Penjualan')
plt.legend()
plt.grid(True)
plt.show()

"""Subplot pada Line Chart"""

# subplot, 2 baris 1 kolom, panjang 10 inch, tinggi 8 inchi
fig, axs = plt.subplots(2, 1, figsize=(10,8))

# plot pertama untuk product C
axs[0].plot(months, product_C_sales, label='Product C', color='green', marker='d')
axs[0].set_title('Penjualan Product C per Bulan')
axs[0].set_xlabel('Bulan')
axs[0].set_ylabel('Jumlah Penjualan')
axs[0].legend()
axs[0].grid('True')

# plot pertama untuk product D
axs[1].plot(months, product_D_sales, label='Product D', color='purple', marker='s')
axs[1].set_title('Penjualan Product D per Bulan')
axs[1].set_xlabel('Bulan')
axs[1].set_ylabel('Jumlah Penjualan')
axs[1].legend()
axs[1].grid('True')

plt.tight_layout()
plt.show()