# -*- coding: utf-8 -*-
"""praktikum05

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M8mqvQEGCQtYFMql3rqP20UgGiLqtqui

**Praktikum Scattaer Plot**

**Anggota Kelompok 19:**

*   Dewi Nuraini - 0110122122
*   Muhammad Daffa Shafwan - 0110222275
*   Muhammad Saputra Adi Firmansyah - 0110222105
"""

import matplotlib.pyplot as plt

# Data dummy
suhu = [20, 22, 24, 26, 28, 30, 32, 34, 36]
penjualan = [50, 60, 70, 90, 100, 130, 150, 180, 200]

# Membuat scatter plot
plt.scatter(suhu, penjualan, color='blue')
plt.title('Hubungan Penjualan Es Krim dan Suhu')
plt.xlabel('Suhu (°C)')
plt.ylabel('Penjualan Es Krim')
plt.show()

"""**Kustomisasi Scatter Plot**"""

import matplotlib.pyplot as plt

# Data Dummy
suhu = [20, 22, 24, 26, 28, 30, 32, 34, 36]
penjualan = [50, 60, 70, 90, 100, 130, 150, 180, 200]

# Kustomisasi scatter plot
plt.scatter(suhu, penjualan, color='orange', s=100, edgecolors='black', alpha=0.7)
plt.title('Hubungan Penjualan Es Krim dan Suhu')
plt.xlabel('Suhu (°C)')
plt.ylabel('Penjualan Es Krim')
plt.grid(True)
plt.show()

"""**Menambahkan Scatter Plot**"""

import matplotlib.pyplot as plt

# Data Dummy
suhu = [20, 22, 24, 26, 28, 30, 32, 34, 36]

# Data tambahan untuk kategori hari
penjualan_kerja = [50, 60, 70, 80, 90, 100, 110, 120, 130]
penjualan_akhir_pekan = [60, 70, 80, 100, 110, 120, 140, 160, 200]

# Scatter plot multiple
plt.scatter(suhu, penjualan_kerja, color='green', label='Hari Kerja', s=80)
plt.scatter(suhu, penjualan_akhir_pekan, color='purple', label='Akhir Pekan', s=80)
plt.title('Penjualan Es Krim Berdasarkan Hari')
plt.xlabel('Suhu (°C)')
plt.ylabel('Penjualan Es Krim')
plt.legend()
plt.grid(True)

"""**Scatter Plot Untuk Melihat Hubungan Data dengan Beberapa Variabel**"""

import matplotlib.pyplot as plt

# Data dummy
suhu = [20, 22, 24, 26, 28, 30, 32, 34, 36]
penjualan = [50, 60, 70, 90, 100, 130, 150, 180, 200]

# Data Tambahan
kelembapan = [60, 65, 70, 75, 80, 85, 90, 95, 100]
ukuran_titik = [200, 220, 240, 260, 280, 300, 320, 340, 360]

# Scatter plot dengan ukuran dan warna yang bervariasi
plt.scatter(suhu, penjualan, c=kelembapan, cmap='coolwarm', s=ukuran_titik, alpha=0.6)
plt.title('Hubungan Penjualan, Suhu dan Kelembapan')
plt.xlabel('Suhu (°C)')
plt.ylabel('Penjualan Es Krim')
plt.colorbar(label='Kelembapan (%)')
plt.show()