# -*- coding: utf-8 -*-
"""Praktikum4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dkclguoL1KA5t7w2AMH3sSRC1oNUn5wu

**PRAKTIKUM BAR CHART**

**Anggota Kelompok 19:**
*   Dewi Nuraini - 0110122122
*   Muhammad Daffa Shafwan - 0110222275
*   Muhammad Saputra Adi Firmansyah - 0110222105
"""

import matplotlib.pyplot as plt

# data
jurusan = [
    'Ilmu Komputer',
    'Teknik Informatika',
    'Sistem Informasi',
    'Data Science',
]

jumlah_mahasiswa = [120, 150, 100, 80]

# membuat basic bar chart
plt.bar(jurusan, jumlah_mahasiswa, color=['blue', 'orange', 'green', 'red'])
plt.xlabel('Jurusan')
plt.ylabel('Jumlah Mahasiswa')
plt.title('Jumlah Mahasiswa Per Jurusan')
plt.show()

"""**a. Basic Bar Chart dengan Matplotlib**"""

from matplotlib.lines import lineStyles
import matplotlib.pyplot as plt

# data
jurusan = [
    'Ilmu Komputer',
    'Teknik Informatika',
    'Sistem Informasi',
    'Data Science',
]

jumlah_mahasiswa = [120, 150, 100, 80]

# membuat basic bar chart
plt.bar(jurusan, jumlah_mahasiswa, color=['blue', 'orange', 'green', 'red'])
plt.title('Jumlah Mahasiswa Per Jurusan')
plt.xlabel('Jurusan')
plt.ylabel('Jumlah Mahasiswa')
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""**b. Kustomisasi Basic Bar Chart**"""

from matplotlib.lines import lineStyles
import matplotlib.pyplot as plt

# data
jurusan = [
    'Ilmu Komputer',
    'Teknik Informatika',
    'Sistem Informasi',
    'Data Science',
]

jumlah_mahasiswa = [120, 150, 100, 80]

# membuat basic bar chart
plt.bar(jurusan, jumlah_mahasiswa, color=['blue', 'orange', 'green', 'red'])
plt.title('Jumlah Mahasiswa Per Jurusan')
plt.xlabel('Jurusan')
plt.ylabel('Jumlah Mahasiswa')
plt.xticks(rotation=45)

# menambahkan label pada batang
for i, v in enumerate(jumlah_mahasiswa):
    plt.text(i, v + 5, str(v), ha='center')

plt.show()

"""**c. Multiple Bar Chart**"""

from matplotlib.lines import lineStyles
import matplotlib.pyplot as plt

# data
jurusan = [
    'Ilmu Komputer',
    'Teknik Informatika',
    'Sistem Informasi',
    'Data Science',
]

jumlah_mahasiswa = [120, 150, 100, 80]
jumlah_mahasiswa_2024 = [110, 140, 95, 85]

x = range(len(jurusan))
width = 0.4

plt.bar(x, jumlah_mahasiswa, width, label='2023', color='orange')
plt.bar([p + width for p in x], jumlah_mahasiswa_2024, width=width, label='2024', color='skyblue')


plt.title('Jumlah Mahasiswa Per Jurusan (2023 vs 2024)')
plt.xlabel('Jurusan')
plt.ylabel('Jumlah Mahasiswa')
plt.xticks(rotation=45)
plt.xticks([p + width/2 for p in x], jurusan)
plt.legend()

plt.show()

"""**d. Basic Bar Chart untuk Melihat Pola dan Tren**"""

import matplotlib.pyplot as plt

# data
jurusan = jurusan = ['Ilmu Komputer', 'Teknik Informatika', 'Sistem Informasi', 'Data Science']
tahun = ['2019', '2020', '2021', '2022', '2023']
data =  {
    'Ilmu Komputer': [120, 130, 140, 150, 160],
    'Teknik Informatika': [110, 120, 130, 140, 150],
    'Sistem Informasi': [100, 110, 120, 130, 140],
    'Data Science': [90, 100, 110, 120, 130]
}

width = 0.15
x = range(len(tahun))

# visualisasi masing-masing jurusan
plt.bar(x, data['Ilmu Komputer'], width=width, label='Ilmu Komputer', color='blue')
plt.bar([p + width for p in x], data['Teknik Informatika'], width=width, label='Teknik Informatika', color='orange')
plt.bar([p + width*2 for p in x], data['Sistem Informasi'], width=width, label='Sistem Informasi', color='green')
plt.bar([p + width*3 for p in x], data['Data Science'], width=width, label='Data Science', color='red')

# detail grafik
plt.title('Tren Jumlah Mahasiswa Per Jurusan')
plt.xlabel('Tahun')
plt.ylabel('Jumlah Mahasiswa')
plt.xticks([p + width for p in x], tahun)
plt.legend()

plt.show()